import { describe, expect, it } from "vitest";
import {
  deriveLinkHostname,
  hashStringToHue,
} from "../src/app/logic/link-card";

// `buildLinkCardDescription` moved to `app/logic/card-excerpt.ts` as
// `buildCardExcerpt` in Step 6 of cards-unification — its tests now
// live in `tests/card-excerpt.test.ts`.

describe("deriveLinkHostname", () => {
  it("extracts the hostname from a typical URL", () => {
    expect(deriveLinkHostname("https://nytimes.com/2026/04/24/article")).toBe(
      "nytimes.com",
    );
  });

  it("strips the leading 'www.' so bare and www forms share colouring", () => {
    // If we didn't strip, nytimes.com and www.nytimes.com would hash
    // to different hues and the user would see two different thumbs
    // for what's effectively the same domain.
    expect(deriveLinkHostname("https://www.nytimes.com/section")).toBe(
      "nytimes.com",
    );
  });

  it("preserves subdomains other than www", () => {
    expect(deriveLinkHostname("https://blog.example.com/post")).toBe(
      "blog.example.com",
    );
    expect(deriveLinkHostname("https://docs.python.org/3/")).toBe(
      "docs.python.org",
    );
  });

  it("handles http URLs and ports", () => {
    expect(deriveLinkHostname("http://localhost:3000/path")).toBe("localhost");
  });

  it("returns null for an unparseable URL", () => {
    // Old workspaces may have malformed entries; the card render
    // falls back gracefully to a neutral placeholder when the
    // hostname can't be derived.
    expect(deriveLinkHostname("not a url at all")).toBeNull();
    expect(deriveLinkHostname("")).toBeNull();
  });
});

describe("hashStringToHue", () => {
  it("returns a value in [0, 360)", () => {
    for (const input of ["nytimes.com", "example.com", "x", "", "docs.python.org"]) {
      const hue = hashStringToHue(input);
      expect(hue).toBeGreaterThanOrEqual(0);
      expect(hue).toBeLessThan(360);
    }
  });

  it("is deterministic — same input → same hue", () => {
    // Critical for UX continuity: the thumb colour must be stable
    // across renders (and sessions). A user who sees nytimes.com as
    // red today should see it red tomorrow.
    expect(hashStringToHue("nytimes.com")).toBe(hashStringToHue("nytimes.com"));
  });

  it("spreads different inputs across the hue wheel (not all the same)", () => {
    // Sanity check that the hash isn't degenerate — a few real-world
    // hostnames should land on at least two distinct hues. If this
    // ever starts failing after a "simplification" of the hash, the
    // distribution has likely been killed.
    const hues = new Set(
      ["nytimes.com", "github.com", "wikipedia.org", "stackoverflow.com"].map(
        hashStringToHue,
      ),
    );
    expect(hues.size).toBeGreaterThan(1);
  });

  it("handles empty string without throwing", () => {
    // The seed by itself (5381) mod 360 — just needs to be a valid
    // hue so the render never crashes on a degenerate input.
    expect(Number.isFinite(hashStringToHue(""))).toBe(true);
  });

  it("pins specific hues for well-known hostnames (regression lock)", () => {
    // Exact-value pin so any accidental change to the djb2 constants
    // (e.g. flipping the multiplier sign, shifting the seed, off-by-one
    // on the loop bound) is caught before it silently recolours every
    // user's link thumbs. Values were generated by the current
    // implementation and hand-verified — if this ever needs to change,
    // the change should be deliberate and visible in the diff, not a
    // hash-tuning slip.
    expect(hashStringToHue("nytimes.com")).toBe(99);
    expect(hashStringToHue("github.com")).toBe(63);
    expect(hashStringToHue("abc")).toBe(29);
  });
});
