import { describe, expect, it } from "vitest";
import {
  buildLinkCardDescription,
  deriveLinkHostname,
  hashStringToHue,
} from "../src/app/logic/link-card";

describe("deriveLinkHostname", () => {
  it("extracts the hostname from a typical URL", () => {
    expect(deriveLinkHostname("https://nytimes.com/2026/04/24/article")).toBe(
      "nytimes.com",
    );
  });

  it("strips the leading 'www.' so bare and www forms share colouring", () => {
    // If we didn't strip, nytimes.com and www.nytimes.com would hash
    // to different hues and the user would see two different thumbs
    // for what's effectively the same domain.
    expect(deriveLinkHostname("https://www.nytimes.com/section")).toBe(
      "nytimes.com",
    );
  });

  it("preserves subdomains other than www", () => {
    expect(deriveLinkHostname("https://blog.example.com/post")).toBe(
      "blog.example.com",
    );
    expect(deriveLinkHostname("https://docs.python.org/3/")).toBe(
      "docs.python.org",
    );
  });

  it("handles http URLs and ports", () => {
    expect(deriveLinkHostname("http://localhost:3000/path")).toBe("localhost");
  });

  it("returns null for an unparseable URL", () => {
    // Old workspaces may have malformed entries; the card render
    // falls back gracefully to a neutral placeholder when the
    // hostname can't be derived.
    expect(deriveLinkHostname("not a url at all")).toBeNull();
    expect(deriveLinkHostname("")).toBeNull();
  });
});

describe("hashStringToHue", () => {
  it("returns a value in [0, 360)", () => {
    for (const input of ["nytimes.com", "example.com", "x", "", "docs.python.org"]) {
      const hue = hashStringToHue(input);
      expect(hue).toBeGreaterThanOrEqual(0);
      expect(hue).toBeLessThan(360);
    }
  });

  it("is deterministic — same input → same hue", () => {
    // Critical for UX continuity: the thumb colour must be stable
    // across renders (and sessions). A user who sees nytimes.com as
    // red today should see it red tomorrow.
    expect(hashStringToHue("nytimes.com")).toBe(hashStringToHue("nytimes.com"));
  });

  it("spreads different inputs across the hue wheel (not all the same)", () => {
    // Sanity check that the hash isn't degenerate — a few real-world
    // hostnames should land on at least two distinct hues. If this
    // ever starts failing after a "simplification" of the hash, the
    // distribution has likely been killed.
    const hues = new Set(
      ["nytimes.com", "github.com", "wikipedia.org", "stackoverflow.com"].map(
        hashStringToHue,
      ),
    );
    expect(hues.size).toBeGreaterThan(1);
  });

  it("handles empty string without throwing", () => {
    // The seed by itself (5381) mod 360 — just needs to be a valid
    // hue so the render never crashes on a degenerate input.
    expect(Number.isFinite(hashStringToHue(""))).toBe(true);
  });

  it("pins specific hues for well-known hostnames (regression lock)", () => {
    // Exact-value pin so any accidental change to the djb2 constants
    // (e.g. flipping the multiplier sign, shifting the seed, off-by-one
    // on the loop bound) is caught before it silently recolours every
    // user's link thumbs. Values were generated by the current
    // implementation and hand-verified — if this ever needs to change,
    // the change should be deliberate and visible in the diff, not a
    // hash-tuning slip.
    expect(hashStringToHue("nytimes.com")).toBe(99);
    expect(hashStringToHue("github.com")).toBe(63);
    expect(hashStringToHue("abc")).toBe(29);
  });
});

describe("buildLinkCardDescription", () => {
  it("returns null when the body is just the URL", () => {
    // The "captured-via-bookmarklet, body = URL" case. The thumb
    // already shows the hostname, so a description line reading
    // "https://…" would be pure duplication.
    expect(
      buildLinkCardDescription("https://nytimes.com/article", "https://nytimes.com/article"),
    ).toBeNull();
  });

  it("returns null when the body is empty", () => {
    expect(buildLinkCardDescription("", "https://nytimes.com/")).toBeNull();
  });

  it("strips the URL out of the body while keeping surrounding prose", () => {
    // The doubled-space left behind where the URL was is collapsed by
    // the whitespace-normalisation step, so "Read: <url> — nice" ends
    // up as "Read: — nice" with a single space, not ":  —".
    const body = "Read this tomorrow: https://nytimes.com/article — looks juicy.";
    expect(
      buildLinkCardDescription(body, "https://nytimes.com/article"),
    ).toBe("Read this tomorrow: — looks juicy.");
  });

  it("collapses newlines/runs of whitespace to a single space", () => {
    // The card body is visually one line, so preserving paragraph
    // breaks buys nothing and just truncates more aggressively.
    const body = "Paragraph one.\n\nParagraph two.\n\nParagraph three.";
    expect(buildLinkCardDescription(body, "https://other.com")).toBe(
      "Paragraph one. Paragraph two. Paragraph three.",
    );
  });

  it("truncates long bodies with an ellipsis at the caller-specified max", () => {
    const body = "a".repeat(200);
    const result = buildLinkCardDescription(body, "https://unused.com", 50);
    if (result === null) throw new Error("expected non-null result");
    // Length <= max; ends with the single ellipsis char.
    expect(result.length).toBeLessThanOrEqual(50);
    expect(result.endsWith("\u2026")).toBe(true);
  });

  it("leaves short bodies untruncated (no trailing ellipsis)", () => {
    const body = "A short paragraph.";
    const result = buildLinkCardDescription(body, "https://unused.com");
    if (result === null) throw new Error("expected non-null result");
    expect(result).toBe("A short paragraph.");
    expect(result.endsWith("\u2026")).toBe(false);
  });

  it("does not truncate when the body is exactly at the max-char budget", () => {
    // Boundary pin: exactly `maxChars` long → return unchanged. If the
    // comparison flips from `<=` to `<`, a body landing on the exact
    // limit would grow a phantom ellipsis.
    const body = "a".repeat(50);
    const result = buildLinkCardDescription(body, "https://unused.com", 50);
    if (result === null) throw new Error("expected non-null result");
    expect(result).toBe(body);
    expect(result.length).toBe(50);
    expect(result.endsWith("\u2026")).toBe(false);
  });

  it("trims leading and trailing whitespace from the result", () => {
    // A body like "  hello world  " should read as "hello world" in
    // the card — leading spaces would look like a layout bug, not
    // preserved intent. Pins the outer .trim() step.
    expect(
      buildLinkCardDescription("   hello world   ", "https://unused.com"),
    ).toBe("hello world");
  });

  it("defaults to 160 chars when no max is given", () => {
    // Pin the default — dashboards/cards are designed around this
    // budget; changing it silently would reflow the whole Links grid.
    const body = "a".repeat(200);
    const result = buildLinkCardDescription(body, "https://unused.com");
    if (result === null) throw new Error("expected non-null result");
    expect(result.length).toBeLessThanOrEqual(160);
    expect(result.length).toBe(160);
  });
});
