// @vitest-environment happy-dom
//
// First focused test for `src/app/view/pages/terms-page.ts`. A copy page, so
// the copy *is* the logic: five numbered clauses, and every string in them is
// its own mutant. The file's own header says it is not legal advice and will
// need a lawyer pass — which is exactly why the shipped wording should not be
// able to drift silently. Asserting the clause table whole means a reworded
// obligation shows up as a failing test rather than as a quiet deploy.
//
// Beyond the copy, three things carry structure:
//
//   - **the numbering lives in the heading strings**, deliberately, so the
//     clauses read as "1. …" when someone copies a selection into an email.
//     There is no `<ol>` doing it, so nothing regenerates it if a string
//     loses its prefix.
//   - **the closing line is built from nodes, not markup.** The italic comes
//     from an `<em>` with its own class, appended after a plain `<span>` —
//     the module comment calls this out as the no-innerHTML guard.
//   - **the shell slots.** Eyebrow, structured title, subtitle and the
//     "Last updated" stamp are all passed to `buildStaticPageShell`, which
//     has its own suite; here it is enough to prove each argument arrived.

import { describe, expect, it, vi } from "vitest";
import { buildTermsPage } from "../src/app/view/pages/terms-page";

function mount() {
  const onSelectMenuItem = vi.fn();
  const page = buildTermsPage({ onSelectMenuItem });
  return { page, onSelectMenuItem };
}

const clauses = (page: HTMLElement): HTMLElement[] => [
  ...page.querySelectorAll<HTMLElement>(".prose > .static-section"),
];

/** `["h2.static-h2", "p.static-paragraph"]` for one element's children. */
const childShape = (parent: Element): string[] =>
  [...parent.children].map((child) => `${child.tagName.toLowerCase()}.${child.className}`);

describe("buildTermsPage shell", () => {
  it("fills every header slot the shell offers", () => {
    const { page } = mount();

    expect(page.className).toBe("static-page");
    expect(page.querySelector(".static-page-eyebrow")?.textContent).toBe("Terms of use");
    expect(page.querySelector(".static-page-subtitle")?.textContent).toBe(
      "By using Sutrapad you agree to a small number of reasonable things. Here they are.",
    );
    expect(page.querySelector(".static-page-meta")?.textContent).toBe(
      "Last updated · April 2026",
    );
  });

  it("emphasises the second half of the title", () => {
    const { page } = mount();
    const title = page.querySelector(".static-page-title");

    expect(title?.textContent).toBe("The handshake.");
    // Built as a DOM `<em>`, never parsed from a markup string.
    expect(title?.querySelector("em")?.textContent).toBe("handshake.");
  });

  it("offers no back link", () => {
    // Terms is reached from the footer, which stays on screen — the shell's
    // back link would point at a page the user did not come from.
    const { page } = mount();

    expect(page.querySelector(".static-page-back")).toBeNull();
  });
});

describe("buildTermsPage clauses", () => {
  it("renders the five clauses in order, numbering included", () => {
    // The numbers are part of the heading strings, not generated by an
    // `<ol>` — nothing puts them back if one goes missing.
    const { page } = mount();

    expect(clauses(page).map((section) => section.querySelector(".static-h2")?.textContent)).toEqual([
      "1. Your notes are yours",
      "2. The software is as-is",
      "3. Don't use Sutrapad for harm",
      "4. We can change these terms",
      "5. Governing law",
    ]);
  });

  it("carries each clause's obligation verbatim", () => {
    const { page } = mount();

    expect(clauses(page).map((section) => section.querySelector(".static-paragraph")?.textContent)).toEqual([
      "You own everything you write in Sutrapad. We claim no license, no copyright, no editorial control.",
      "Sutrapad is provided without warranty of any kind. If it eats your notes — and it shouldn't, but software is software — we are sorry, but we cannot be held liable.",
      "Don't use the capture system to scrape sites at scale. Don't use Sutrapad to organise material that's illegal where you live. Common sense.",
      "If we change anything material, we'll surface it as a banner the next time you open Sutrapad — not as an email blast.",
      "Czech law, with a soft spot for common sense. Disputes go to the courts of Praha.",
    ]);
  });

  it("gives each clause a heading above exactly one paragraph", () => {
    const { page } = mount();

    expect(clauses(page).map((section) => childShape(section))).toEqual(
      Array.from({ length: 5 }, () => ["h2.static-h2", "p.static-paragraph"]),
    );
  });

  it("keeps the clauses at h2, under the page's single h1", () => {
    // The static shell owns the `<h1>`; a clause promoted to h1 would break
    // the document outline on a page people do read top to bottom.
    const { page } = mount();

    expect(page.querySelectorAll("h1")).toHaveLength(1);
    expect(page.querySelectorAll(".prose h2")).toHaveLength(5);
  });
});

describe("buildTermsPage closing call to action", () => {
  it("puts the CTA last, after every clause", () => {
    const { page } = mount();

    expect([...(page.querySelector(".prose")?.children ?? [])].map((child) => child.className)).toEqual([
      "static-section",
      "static-section",
      "static-section",
      "static-section",
      "static-section",
      "static-foot-cta",
    ]);
  });

  it("builds the closing line from a lead span and an emphasised tail", () => {
    // Two nodes, not one interpolated string: the italic is a real `<em>`
    // with its own class, so no markup ever gets parsed here.
    const { page } = mount();
    const text = page.querySelector(".static-foot-cta-text");

    expect(text?.className).toBe("static-foot-cta-text muted");
    expect(text?.textContent).toBe("In a phrase: be kind, take your data with you.");
    expect([...(text?.children ?? [])].map((child) => child.tagName.toLowerCase())).toEqual([
      "span",
      "em",
    ]);
    expect(text?.querySelector("em")?.className).toBe("static-foot-cta-emphasis");
    expect(text?.querySelector("em")?.textContent).toBe("be kind, take your data with you.");
  });

  it("routes the single action back to Today", () => {
    const { page, onSelectMenuItem } = mount();
    const actions = page.querySelector(".static-foot-cta-actions");
    const button = actions?.querySelector<HTMLButtonElement>("button");

    expect(actions?.children).toHaveLength(1);
    expect(button?.type).toBe("button");
    expect(button?.className).toBe("button button-primary");
    expect(button?.textContent).toBe("Back to Today");

    button?.click();
    expect(onSelectMenuItem).toHaveBeenCalledExactlyOnceWith("home");
  });

  it("puts the closing line above the action row", () => {
    const { page } = mount();

    expect(
      [...(page.querySelector(".static-foot-cta")?.children ?? [])].map((c) => c.className),
    ).toEqual(["static-foot-cta-text muted", "static-foot-cta-actions"]);
  });
});
